dist: trusty
sudo: false
language: python
python:
- "3.2"
- "3.3"
- "3.4"
- "3.5"
- "3.6"
- "3.7-dev"
before_install:
- pyflakes=pyflakes
- if [[ $TRAVIS_PYTHON_VERSION = 3.[23] ]]; then pyflakes='pyflakes<2'; fi
- if [[ $TRAVIS_PYTHON_VERSION = 3.2 ]]; then if_pygments=:; fi
install:
- pip install pydiatra $pyflakes
- $if_pygments pip install restructuredtext-lint pygments
script:
- python3 -m pydiatra .
- python3 -m pyflakes .
- $if_pygments restructuredtext-lint --encoding=UTF-8 README
- make
- timeout 1 ./pyhttpsserver 0 0; [ $? -eq 124 ]

# vim:ts=2 sts=2 sw=2 et
